### ISSUE TITLE
[Proposal] Consider `estimateItemSize` in addition to `itemSize.`

### ISSUE THREAD

**Issue by tomokitakahashi** [ra1028/Carbon#12]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/Carbon/blob/master/README.md) and [documents](https://ra1028.github.io/Carbon).  
- [x] Searched [existing issues](https://github.com/ra1028/Carbon/issues) for ensure not duplicated.  

## Description
I used UICollectionViewFlowLayout to implement a collectionView where collectionView.height and collectionView.contentSize.height are equal and the width of the cell is dynamic. Then, I set `estimatedItemSize` on `prepare ()` method(didn't set `itemSize`). 
It makes `UICollectionViewFlowLayoutBreakForInvalidSizes` of layout error.(I called `layoutIfNeeded` after `reloadData`)

I resolved to set `itemSize` on `prepare()`.

Found Carbon [handle](https://github.com/ra1028/Carbon/blob/master/Sources/Adapters/UICollectionViewFlowLayoutAdapter.swift#L10) for only `itemSize`.

[Apple Document](https://developer.apple.com/documentation/uikit/uicollectionviewflowlayout/1617709-estimateditemsize) don't say need both `estimatedItemSize` and `itemSize`.

## Proposed Solution
Carbon handle both `itemSize` and estimatedItemSize or write doc about `estimatedItemSize`. (It may not be necessary because `itemSize` is already written 🤔 )

**Comment by ra1028** [comment]
Hi @tomokitakahashi ,

The dynamic sizing API in UICollectionView is so delicate that it's hard to know your situation unless looking at the entire implementation.
At least it worked as far as I tried before.

FYI, when using dynamic sizing, the diffing animation in UICollectionView will glitch.
I searched for a smart solution to this bug but couldn't found.
If you want to have both dynamic sizing and diffing animation, you will need to do a legacy implementation, but that's life.

**Comment by tomokitakahashi** [comment]
Thanks @ra1028 !
I didn't know your think !  I trying to diff animation too 👍 

I'll close this issue 😄

**Comment by Zasuk** [comment]
as @ra1028 said dynamic sizing API in UICollectionView is tricky....
you can try to get the same result using autolayout to calculate the cell size for each component.

I haven't tried but this should work:
- storing a View for all components
- configure it in referenceSize method
- use auto layout to get the compressed size
- return the calculated size in referenceSize method

This is basically the old way to implement dynamic cell sizing. You need to test it because for some cases it can affect the performance (caching the calculated sizes for example in adapter can improve it)
